name: CI

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '42 5 * * 6'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: https://git.fablab-altmuehlfranken.de/fmueller/fabcal.git#main
          pull: true
          tags: ghcr.io/FabLab-Altmuehlfranken/fabcal-docker:latest
          push: true
